Mappings:
  RegionEC2InstanceAMIMap:
    us-east-2:
      HVM: ami-0b0dcb5067f052a63 
    us-east-1:
      HVM: ami-0beaa649c482330f7


Parameters:
  EC2InstanceType:
    Description: Instancia EC2
    Type: String
    
Resources:
  PosMackCFInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !FindInMap
        - RegionEC2InstanceAMIMap
        - !Ref 'AWS::Region'
        - HVM
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref HTTPSecurityGroup

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Porta 80 e Porta 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
